site_name: Pirataria
site_url: https://c-pirataria.github.io/megathread/

repo_name: c-pirataria/megathread
repo_url: https://github.com/c-pirataria/megathread

nav:
  - Início: 
    - index.md
    - faq.md
    - glossario.md
  - Guias:
    - guias.md
    - virustotal.md
    - coletanea-uteis-privacidade-seguranca.md
    - discord.md
  - Sites de Uso Geral: 
    - sites-geral.md
  - Jogos:
    - jogos.md
    - jogos-piratas.md
    - emuladores-e-roms.md
  - Educação:
    - educacional.md
    - livros.md
  - Entretenimento: 
    - esportes.md
    - filmes-e-tv.md
    - anime.md
    - musica.md
  - Mobile: 
    - mobile.md
  - Ferramentas: 
    - ferramentas.md
  - Softwares: 
    - softwares.md
  - Trackers:
    - trackers.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: pt

extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html
  - toc

plugins:
  - glightbox
  - search

theme:
  logo: assets/grande.png
  favicon: assets/grande.png
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Roboto
  palette:
    scheme: slate
    primary: black
    accent: light-blue

extra:
  generator: false
  social:
    - icon: fontawesome/brands/reddit 
      link: https://reddit.com/r/pirataria
