site_name: Pirataria
site_url: https://c-pirataria.github.io/megathread/

repo_name: c-pirataria/megathread
repo_url: https://github.com/c-pirataria/megathread

nav:
  - Início: 
    - index.md
    - faq.md
    - glossario.md
    - dicionario.md
  - Sites de Uso Geral: sites-geral.md
  - Jogos: jogos.md
  - Anime: anime.md
  - Música: musica.md
  - Educacional: educacional.md
  - Livros: livros.md
  - Emuladores/ROMs: emuladores-e-roms.md
  - Esportes: esportes.md
  - Filmes/TV: filmes-e-tv.md
  - Mobile: mobile.md
  - Ferramentas: ferramentas.md
  - Softwares: softwares.md
  - Guias: guias.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: pt

extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - glightbox
  - search

theme:
  logo: assets/grande.png
  favicon: assets/grande.png
  name: material
  language: pt-BR
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Roboto
  palette:
    scheme: slate
    primary: black
    accent: light-blue

extra:
  generator: false
  social:
    - icon: fontawesome/brands/reddit 
      link: https://reddit.com/r/pirataria