name: Codeberg mirroring action
on:
  push:
    branches:
      - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/pirataria/megathread.git'
          GIT_USERNAME: 'pirataria'
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}